<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>false</UseWindowsForms>
    <Configurations>Debug;Release;Test</Configurations>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>AutoTrackR2.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CSCore" Version="1.2.1.2" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\AVSQN.png" />
    <None Remove="Assets\BlightVeil.png" />
    <None Remove="Assets\BOBGREL.png" />
    <None Remove="Assets\chibifox.png" />
    <None Remove="Assets\D3VL.png" />
    <None Remove="Assets\EMP.png" />
    <None Remove="Assets\Gankhub.png" />
    <None Remove="Assets\HEX.png" />
    <None Remove="Assets\HIT.png" />
    <None Remove="Assets\MAMMON.png" />
    <None Remove="Assets\NMOS.png" />
    <None Remove="Assets\NW.png" />
    <None Remove="Assets\RACKETEERS.png" />
    <None Remove="Assets\SHADOWMOSES.png" />
    <None Remove="Assets\VOX.png" />
    <None Remove="Assets\WRITH.png" />
    <None Remove="Fonts\Orbitron-Bold.ttf" />
    <None Remove="Fonts\Roboto-Regular.ttf" />
    <None Remove="Assets\EnemyPlayer_Kill.mp3" />
    <None Remove="Assets\EnemyShip_Destruction.mp3" />
    <None Remove="Assets\EnemyShip_SoftDeath.mp3" />
    <None Remove="Assets\PlayerSpawn.mp3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AutoTrackR2.ico" />
  </ItemGroup>

<ItemGroup>
    <Resource Include="Assets\BlightVeil.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Gankhub.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\NMOS.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\AVSQN.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\BOBGREL.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\chibifox.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\D3VL.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\EMP.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\GN.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\AutoTrackR.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\HEX.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\HIT.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\MAMMON.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\NW.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\RACKETEERS.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\SHADOWMOSES.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\VOX.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\WRITH.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="config.ini" />
    <Resource Include="Fonts\Orbitron-Bold.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Roboto-Regular.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <AppData Include="Assets\videorecord.ahk" CopyToOutputDirectory="PreserveNewest" />
    <AppData Include="Assets\visorwipe.ahk" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <None Update="KillTrackR_MainScript.ps1" CopyToOutputDirectory="Always" />
    <None Update="update.ps1" CopyToOutputDirectory="Always" />
    <None Include="Assets\EnemyPlayer_Kill.mp3" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Assets\EnemyShip_Destruction.mp3" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Assets\EnemyShip_SoftDeath.mp3" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Assets\PlayerSpawn.mp3" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <Target Name="CopyAppData" AfterTargets="Build">
    <PropertyGroup>
      <AppDataPath>$(LocalAppData)\AutoTrackR2</AppDataPath>
    </PropertyGroup>

    <MakeDir Directories="$(AppDataPath)" />

    <Copy SourceFiles="@(AppData)" 
          DestinationFolder="$(AppDataPath)" 
          SkipUnchangedFiles="true" />
  </Target>

</Project>
